### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [deepseagirl/easylkb#2]
Hello!

I found your project from https://hackaday.com/2023/11/22/linux-fu-easy-kernel-debugging/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

As I see in https://pypi.org/project/easylkb/ : 
> License: MIT License

but I can't find this in the repository itself.

**Comment by deepseagirl** [comment]
so sorry for the delay - I will add proper license info soon, hopefully this week! thank you for your inquiry 💓

**Comment by deepseagirl** [comment]
license file was added -
https://github.com/deepseagirl/easylkb/blob/main/LICENSE

**Comment by deepseagirl** [comment]
license file was added -
https://github.com/deepseagirl/easylkb/blob/main/LICENSE

**Comment by vazhnov** [comment]
The MIT license! Amazing! Thank you!
